// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: picovpnd.proto

package picovpnd

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserAddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAddRequest) Reset() {
	*x = UserAddRequest{}
	mi := &file_picovpnd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAddRequest) ProtoMessage() {}

func (x *UserAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_picovpnd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAddRequest.ProtoReflect.Descriptor instead.
func (*UserAddRequest) Descriptor() ([]byte, []int) {
	return file_picovpnd_proto_rawDescGZIP(), []int{0}
}

func (x *UserAddRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserAddRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_picovpnd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_picovpnd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_picovpnd_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UserLockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLockRequest) Reset() {
	*x = UserLockRequest{}
	mi := &file_picovpnd_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLockRequest) ProtoMessage() {}

func (x *UserLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_picovpnd_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLockRequest.ProtoReflect.Descriptor instead.
func (*UserLockRequest) Descriptor() ([]byte, []int) {
	return file_picovpnd_proto_rawDescGZIP(), []int{2}
}

func (x *UserLockRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type UserUnlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUnlockRequest) Reset() {
	*x = UserUnlockRequest{}
	mi := &file_picovpnd_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUnlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUnlockRequest) ProtoMessage() {}

func (x *UserUnlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_picovpnd_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUnlockRequest.ProtoReflect.Descriptor instead.
func (*UserUnlockRequest) Descriptor() ([]byte, []int) {
	return file_picovpnd_proto_rawDescGZIP(), []int{3}
}

func (x *UserUnlockRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type UserDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDeleteRequest) Reset() {
	*x = UserDeleteRequest{}
	mi := &file_picovpnd_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDeleteRequest) ProtoMessage() {}

func (x *UserDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_picovpnd_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDeleteRequest.ProtoReflect.Descriptor instead.
func (*UserDeleteRequest) Descriptor() ([]byte, []int) {
	return file_picovpnd_proto_rawDescGZIP(), []int{4}
}

func (x *UserDeleteRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type UserChangePasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserChangePasswordRequest) Reset() {
	*x = UserChangePasswordRequest{}
	mi := &file_picovpnd_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserChangePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserChangePasswordRequest) ProtoMessage() {}

func (x *UserChangePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_picovpnd_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserChangePasswordRequest.ProtoReflect.Descriptor instead.
func (*UserChangePasswordRequest) Descriptor() ([]byte, []int) {
	return file_picovpnd_proto_rawDescGZIP(), []int{5}
}

func (x *UserChangePasswordRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserChangePasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_picovpnd_proto protoreflect.FileDescriptor

const file_picovpnd_proto_rawDesc = "" +
	"\n" +
	"\x0epicovpnd.proto\x12\n" +
	"helloworld\"H\n" +
	"\x0eUserAddRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\" \n" +
	"\bResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"-\n" +
	"\x0fUserLockRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"/\n" +
	"\x11UserUnlockRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"/\n" +
	"\x11UserDeleteRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"S\n" +
	"\x19UserChangePasswordRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword2\xf3\x02\n" +
	"\x12OpenConnectService\x12=\n" +
	"\aUserAdd\x12\x1a.helloworld.UserAddRequest\x1a\x14.helloworld.Response\"\x00\x12?\n" +
	"\bUserLock\x12\x1b.helloworld.UserLockRequest\x1a\x14.helloworld.Response\"\x00\x12C\n" +
	"\n" +
	"UserUnlock\x12\x1d.helloworld.UserUnlockRequest\x1a\x14.helloworld.Response\"\x00\x12C\n" +
	"\n" +
	"UserDelete\x12\x1d.helloworld.UserDeleteRequest\x1a\x14.helloworld.Response\"\x00\x12S\n" +
	"\x12UserChangePassword\x12%.helloworld.UserChangePasswordRequest\x1a\x14.helloworld.Response\"\x00B+Z)github.com/anatolio-deb/picovpnd/picovpndb\x06proto3"

var (
	file_picovpnd_proto_rawDescOnce sync.Once
	file_picovpnd_proto_rawDescData []byte
)

func file_picovpnd_proto_rawDescGZIP() []byte {
	file_picovpnd_proto_rawDescOnce.Do(func() {
		file_picovpnd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_picovpnd_proto_rawDesc), len(file_picovpnd_proto_rawDesc)))
	})
	return file_picovpnd_proto_rawDescData
}

var file_picovpnd_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_picovpnd_proto_goTypes = []any{
	(*UserAddRequest)(nil),            // 0: helloworld.UserAddRequest
	(*Response)(nil),                  // 1: helloworld.Response
	(*UserLockRequest)(nil),           // 2: helloworld.UserLockRequest
	(*UserUnlockRequest)(nil),         // 3: helloworld.UserUnlockRequest
	(*UserDeleteRequest)(nil),         // 4: helloworld.UserDeleteRequest
	(*UserChangePasswordRequest)(nil), // 5: helloworld.UserChangePasswordRequest
}
var file_picovpnd_proto_depIdxs = []int32{
	0, // 0: helloworld.OpenConnectService.UserAdd:input_type -> helloworld.UserAddRequest
	2, // 1: helloworld.OpenConnectService.UserLock:input_type -> helloworld.UserLockRequest
	3, // 2: helloworld.OpenConnectService.UserUnlock:input_type -> helloworld.UserUnlockRequest
	4, // 3: helloworld.OpenConnectService.UserDelete:input_type -> helloworld.UserDeleteRequest
	5, // 4: helloworld.OpenConnectService.UserChangePassword:input_type -> helloworld.UserChangePasswordRequest
	1, // 5: helloworld.OpenConnectService.UserAdd:output_type -> helloworld.Response
	1, // 6: helloworld.OpenConnectService.UserLock:output_type -> helloworld.Response
	1, // 7: helloworld.OpenConnectService.UserUnlock:output_type -> helloworld.Response
	1, // 8: helloworld.OpenConnectService.UserDelete:output_type -> helloworld.Response
	1, // 9: helloworld.OpenConnectService.UserChangePassword:output_type -> helloworld.Response
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_picovpnd_proto_init() }
func file_picovpnd_proto_init() {
	if File_picovpnd_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_picovpnd_proto_rawDesc), len(file_picovpnd_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_picovpnd_proto_goTypes,
		DependencyIndexes: file_picovpnd_proto_depIdxs,
		MessageInfos:      file_picovpnd_proto_msgTypes,
	}.Build()
	File_picovpnd_proto = out.File
	file_picovpnd_proto_goTypes = nil
	file_picovpnd_proto_depIdxs = nil
}
