// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: grpc/picovpnd.proto

package picovpnd

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CertAndKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cert          string                 `protobuf:"bytes,1,opt,name=cert,proto3" json:"cert,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertAndKeyResponse) Reset() {
	*x = CertAndKeyResponse{}
	mi := &file_grpc_picovpnd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertAndKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertAndKeyResponse) ProtoMessage() {}

func (x *CertAndKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_picovpnd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertAndKeyResponse.ProtoReflect.Descriptor instead.
func (*CertAndKeyResponse) Descriptor() ([]byte, []int) {
	return file_grpc_picovpnd_proto_rawDescGZIP(), []int{0}
}

func (x *CertAndKeyResponse) GetCert() string {
	if x != nil {
		return x.Cert
	}
	return ""
}

func (x *CertAndKeyResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type UserAddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"` // Token for authentication
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAddRequest) Reset() {
	*x = UserAddRequest{}
	mi := &file_grpc_picovpnd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAddRequest) ProtoMessage() {}

func (x *UserAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_picovpnd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAddRequest.ProtoReflect.Descriptor instead.
func (*UserAddRequest) Descriptor() ([]byte, []int) {
	return file_grpc_picovpnd_proto_rawDescGZIP(), []int{1}
}

func (x *UserAddRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserAddRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserAddRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_grpc_picovpnd_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_picovpnd_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_grpc_picovpnd_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UserLockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"` // Token for authentication
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLockRequest) Reset() {
	*x = UserLockRequest{}
	mi := &file_grpc_picovpnd_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLockRequest) ProtoMessage() {}

func (x *UserLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_picovpnd_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLockRequest.ProtoReflect.Descriptor instead.
func (*UserLockRequest) Descriptor() ([]byte, []int) {
	return file_grpc_picovpnd_proto_rawDescGZIP(), []int{3}
}

func (x *UserLockRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserLockRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type UserUnlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"` // Token for authentication
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUnlockRequest) Reset() {
	*x = UserUnlockRequest{}
	mi := &file_grpc_picovpnd_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUnlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUnlockRequest) ProtoMessage() {}

func (x *UserUnlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_picovpnd_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUnlockRequest.ProtoReflect.Descriptor instead.
func (*UserUnlockRequest) Descriptor() ([]byte, []int) {
	return file_grpc_picovpnd_proto_rawDescGZIP(), []int{4}
}

func (x *UserUnlockRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserUnlockRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type UserDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"` // Token for authentication
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDeleteRequest) Reset() {
	*x = UserDeleteRequest{}
	mi := &file_grpc_picovpnd_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDeleteRequest) ProtoMessage() {}

func (x *UserDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_picovpnd_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDeleteRequest.ProtoReflect.Descriptor instead.
func (*UserDeleteRequest) Descriptor() ([]byte, []int) {
	return file_grpc_picovpnd_proto_rawDescGZIP(), []int{5}
}

func (x *UserDeleteRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserDeleteRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type UserChangePasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"` // Token for authentication
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserChangePasswordRequest) Reset() {
	*x = UserChangePasswordRequest{}
	mi := &file_grpc_picovpnd_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserChangePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserChangePasswordRequest) ProtoMessage() {}

func (x *UserChangePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_picovpnd_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserChangePasswordRequest.ProtoReflect.Descriptor instead.
func (*UserChangePasswordRequest) Descriptor() ([]byte, []int) {
	return file_grpc_picovpnd_proto_rawDescGZIP(), []int{6}
}

func (x *UserChangePasswordRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserChangePasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserChangePasswordRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type AuthenticateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // Token for authentication
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateRequest) Reset() {
	*x = AuthenticateRequest{}
	mi := &file_grpc_picovpnd_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateRequest) ProtoMessage() {}

func (x *AuthenticateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_picovpnd_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return file_grpc_picovpnd_proto_rawDescGZIP(), []int{7}
}

func (x *AuthenticateRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_grpc_picovpnd_proto protoreflect.FileDescriptor

const file_grpc_picovpnd_proto_rawDesc = "" +
	"\n" +
	"\x13grpc/picovpnd.proto\x12\n" +
	"helloworld\":\n" +
	"\x12CertAndKeyResponse\x12\x12\n" +
	"\x04cert\x18\x01 \x01(\tR\x04cert\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"^\n" +
	"\x0eUserAddRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\" \n" +
	"\bResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"C\n" +
	"\x0fUserLockRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"E\n" +
	"\x11UserUnlockRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"E\n" +
	"\x11UserDeleteRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"i\n" +
	"\x19UserChangePasswordRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"+\n" +
	"\x13AuthenticateRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token2\xc7\x03\n" +
	"\x12OpenConnectService\x12=\n" +
	"\aUserAdd\x12\x1a.helloworld.UserAddRequest\x1a\x14.helloworld.Response\"\x00\x12?\n" +
	"\bUserLock\x12\x1b.helloworld.UserLockRequest\x1a\x14.helloworld.Response\"\x00\x12C\n" +
	"\n" +
	"UserUnlock\x12\x1d.helloworld.UserUnlockRequest\x1a\x14.helloworld.Response\"\x00\x12C\n" +
	"\n" +
	"UserDelete\x12\x1d.helloworld.UserDeleteRequest\x1a\x14.helloworld.Response\"\x00\x12S\n" +
	"\x12UserChangePassword\x12%.helloworld.UserChangePasswordRequest\x1a\x14.helloworld.Response\"\x00\x12R\n" +
	"\rGetCertAndKey\x12\x1f.helloworld.AuthenticateRequest\x1a\x1e.helloworld.CertAndKeyResponse\"\x00B+Z)github.com/anatolio-deb/picovpnd/picovpndb\x06proto3"

var (
	file_grpc_picovpnd_proto_rawDescOnce sync.Once
	file_grpc_picovpnd_proto_rawDescData []byte
)

func file_grpc_picovpnd_proto_rawDescGZIP() []byte {
	file_grpc_picovpnd_proto_rawDescOnce.Do(func() {
		file_grpc_picovpnd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_picovpnd_proto_rawDesc), len(file_grpc_picovpnd_proto_rawDesc)))
	})
	return file_grpc_picovpnd_proto_rawDescData
}

var file_grpc_picovpnd_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_grpc_picovpnd_proto_goTypes = []any{
	(*CertAndKeyResponse)(nil),        // 0: helloworld.CertAndKeyResponse
	(*UserAddRequest)(nil),            // 1: helloworld.UserAddRequest
	(*Response)(nil),                  // 2: helloworld.Response
	(*UserLockRequest)(nil),           // 3: helloworld.UserLockRequest
	(*UserUnlockRequest)(nil),         // 4: helloworld.UserUnlockRequest
	(*UserDeleteRequest)(nil),         // 5: helloworld.UserDeleteRequest
	(*UserChangePasswordRequest)(nil), // 6: helloworld.UserChangePasswordRequest
	(*AuthenticateRequest)(nil),       // 7: helloworld.AuthenticateRequest
}
var file_grpc_picovpnd_proto_depIdxs = []int32{
	1, // 0: helloworld.OpenConnectService.UserAdd:input_type -> helloworld.UserAddRequest
	3, // 1: helloworld.OpenConnectService.UserLock:input_type -> helloworld.UserLockRequest
	4, // 2: helloworld.OpenConnectService.UserUnlock:input_type -> helloworld.UserUnlockRequest
	5, // 3: helloworld.OpenConnectService.UserDelete:input_type -> helloworld.UserDeleteRequest
	6, // 4: helloworld.OpenConnectService.UserChangePassword:input_type -> helloworld.UserChangePasswordRequest
	7, // 5: helloworld.OpenConnectService.GetCertAndKey:input_type -> helloworld.AuthenticateRequest
	2, // 6: helloworld.OpenConnectService.UserAdd:output_type -> helloworld.Response
	2, // 7: helloworld.OpenConnectService.UserLock:output_type -> helloworld.Response
	2, // 8: helloworld.OpenConnectService.UserUnlock:output_type -> helloworld.Response
	2, // 9: helloworld.OpenConnectService.UserDelete:output_type -> helloworld.Response
	2, // 10: helloworld.OpenConnectService.UserChangePassword:output_type -> helloworld.Response
	0, // 11: helloworld.OpenConnectService.GetCertAndKey:output_type -> helloworld.CertAndKeyResponse
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_picovpnd_proto_init() }
func file_grpc_picovpnd_proto_init() {
	if File_grpc_picovpnd_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_picovpnd_proto_rawDesc), len(file_grpc_picovpnd_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_picovpnd_proto_goTypes,
		DependencyIndexes: file_grpc_picovpnd_proto_depIdxs,
		MessageInfos:      file_grpc_picovpnd_proto_msgTypes,
	}.Build()
	File_grpc_picovpnd_proto = out.File
	file_grpc_picovpnd_proto_goTypes = nil
	file_grpc_picovpnd_proto_depIdxs = nil
}
