name: Build and Release .deb

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install GoReleaser
        run: |
          go install github.com/goreleaser/goreleaser/v2@latest

      # - name: Build Go binary
      #   run: |
      #     go build -o picovpnd ./picovpn_server/main.go

      # - name: Build .deb package
      #   run: |
      #     fpm -s dir -t deb -n picovpnd -v "${GITHUB_REF_NAME#v}" ./picovpnd=/usr/bin/picovpnd

      - name: Upload to GitHub Release
        run: |
          goreleaser release
        # with:
        #   files: picovpnd_*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.PICOVPN_DAEMON }}